version: 2
sources:
- name: public
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_customers
  - name: _airbyte_raw_discount_codes
  - name: _airbyte_raw_draft_orders
  - name: _airbyte_raw_products
